# Generated by Django 4.1.7 on 2023-08-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedisBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('publish', models.CharField(max_length=32, verbose_name='出版社')),
            ],
            options={
                'verbose_name': 'Redis - 图书',
                'verbose_name_plural': 'Redis - 图书',
                'db_table': 'redis_books',
            },
        ),
    ]
